### ISSUE TITLE
Map view is still not working

### ISSUE THREAD

**Issue by mano-mykingdom** [manumaticx/Ti.DrawerLayout#31]
Map View works fine when setting it as center view for drawer. 

But in my case I want to have both map view and list view on the same page. So I added map and list views to a view and set that as the center view, now map never loads.

**Comment by mano-mykingdom** [comment]
Test case
```
var TiDrawerLayout = require('com.tripvi.drawerlayout');
var Map = require("ti.map");
var win = Ti.UI.createWindow({
	backgroundColor : 'white'
});
var drawer = TiDrawerLayout.createDrawer();
var menu = Ti.UI.createTableView({
	data : [{
		title : "Home"
	}, {
		title : "About"
	}]
});
var wrapperView = Ti.UI.createView({
	backgroundColor : 'orange',
});
wrapperView.add(Ti.UI.createLabel({
	top : 10,
	text : "I would like to place a list view or some other compoent here, now map never loads",
	color : "#fff"
}));
var mapview = Map.createView({
	bottom : 0,
	height : "50%",
	fragmentOnly : true
});
wrapperView.add(mapview);
drawer.setLeftView(menu);
drawer.setCenterView(wrapperView);
win.add(drawer);
win.open();

```

**Comment by mano-mykingdom** [comment]
Created a ticket here [TIMOB-18876](https://jira.appcelerator.org/browse/TIMOB-18876)

**Comment by manumaticx** [comment]
@mano-mykingdom thanks

**Comment by manumaticx** [comment]
Fixed in #36

**Comment by marconealberto** [comment]
this is still happening on my side. 

Ti.DrawerLayout 3.0.1
TiSDK 7.0.0.GA
Android 7.0

The app simply crashes if you put a map as a central view, despite what it's in the ticket.

**Comment by manumaticx** [comment]
@marconealberto can you add the Exception from catlog please?

**Comment by marconealberto** [comment]
ok, found the problem and a workaround:

I tried with this simple code:

```
var Map = require('ti.map');
var mapView = Map.createView();

// create the Drawer
var drawer = TiDrawerLayout.createDrawer({
    leftView: leftView,
    centerView: mapView
});

```

and I was getting:

> W/WindowManager: Failed looking up window
>                                                            java.lang.IllegalArgumentException: Requested window android.view.ViewRootImpl$W@c8032cd does not exist

I made it wait till the window was open:

```
win.addEventListener('open', function(){
   drawer.setCenterView(mapView);
});
```

and it's working. Still don't know what it will happen on a real device.
